version: '3.2'
services:
  adguardhome:
    container_name: adguardhome
    image: adguard/adguardhome
    restart: unless-stopped
    volumes:
      - adguard-config:/opt/adguardhome/work
      - adguard-config:/opt/adguardhome/conf
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
      - "3000:3000/tcp"
      - "853:853/tcp"
      - "784:784/udp"
      - "853:853/udp"
      - "8853:8853/udp"
      - "5443:5443/tcp"
      - "5443:5443/udp"
volumes:
  adguard-config:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.20,nolock,soft,rw,nfsvers=4"
      device: ":/adguard"

